passing args to 'crypsetup open'
latchset/clevis pull request #317
Opened 2021-06-10 15:59 UTC by somewhere-or-other

Quick attempt to allow passing of arbitrary args to 'cryptsetup open' when unlocking volume.  Related to the discussion [here](https://github.com/latchset/clevis/issues/316).

2021-06-10 16:01 UTC, somewhere-or-other commented
This is just a quick, minimally-tested version, so feel free to give feedback here, if I've made any egregious errors, etc.

2021-06-15 08:23 UTC, sarroutbi commented on src/luks/clevis-luks-unlock
> +    echo -n "${pt}" | cryptsetup ${OPENARGS} open -d- "${DEV}" "${NAME}"
echo -n "${pt}" | cryptsetup ${OPENARGS} open -d- "${DEV}" "${NAME}"
                                                 ^-----------------^ SC2086: Double quote to prevent globbing and word splitting.

2021-06-15 14:28 UTC, somewhere-or-other commented on src/luks/clevis-luks-unlock
> +    echo -n "${pt}" | cryptsetup ${OPENARGS} open -d- "${DEV}" "${NAME}"
I considered putting the new `${OPENARGS}`  in double-quotes, but was concerned about what would happen if someone wanted to include a space in their parameter string, like passing two different parameters (eg. `-a -b`, as a contrived example), or a space-separated name/value pair.  From my tests, it seemed as though enclosing `${OPENARGS}` in double-quotes, made `cryptsetup` consider it a single parameter that happened to contain spaces.

For my personal use, I only had one parameter to pass, so it would work either way. I just wanted to make a solution for a more general use case.

If there's a better way to handle this, I'm happy to take suggestions.

2021-06-15 15:07 UTC, sarroutbi commented on src/luks/clevis-luks-unlock
> +    echo -n "${pt}" | cryptsetup ${OPENARGS} open -d- "${DEV}" "${NAME}"
Yes, I had not considered about the issues when using quotes. So change looks good to me.

2021-06-15 15:10 UTC, somewhere-or-other commented on src/luks/clevis-luks-unlock
> +    echo -n "${pt}" | cryptsetup ${OPENARGS} open -d- "${DEV}" "${NAME}"
If I'm being honest, I did put it in quotes in a private/dev repo, and discovered the problem, before squashing it into a single pull request.

2021-06-16 09:38 UTC, sarroutbi commented on src/luks/clevis-luks-unlock
> +    echo -n "${pt}" | cryptsetup ${OPENARGS} open -d- "${DEV}" "${NAME}"
Nice. In my opinion, it can be merged, but let's wait for @sergio-correia to review it.

2021-06-16 09:40 UTC, sarroutbi commented on src/luks/clevis-luks-unlock
> +    echo -n "${pt}" | cryptsetup ${OPENARGS} open -d- "${DEV}" "${NAME}"
As additional improvement, it would be nice to add a test to src/luks/tests to simulate a call to clevis-luks-unlock with a cryptsetup option

2021-06-24 20:19 UTC, somewhere-or-other commented on src/luks/clevis-luks-unlock
> +    echo -n "${pt}" | cryptsetup ${OPENARGS} open -d- "${DEV}" "${NAME}"
@sarroutbi I've just submitted an [initial attempt](https://github.com/latchset/clevis/pull/317/commits/0e74c261c3cf559ec6e169538266baddccaecfa8) at a test.  Basically it just uses a bash function to hijack cryptsetup temporarily, and verifies that the arbitrary value makes it through.

It's very possible I've done something incorrectly, though, so don't just take my word for it. Took me a while to figure out the testing/development environment.  And that's why I'm mostly a sysadmin, not a developer.

2021-07-07 18:10 UTC, somewhere-or-other commented
@sergio-correia @sarroutbi Is there anything I can do to shepherd this process along?  It's not so urgent that it must happen now or anything.  I just wasn't sure what kind of timeframe I could expect something to happen.  It's fine if it takes a while, but it would be helpful to know, even roughly, how long it is likely to take.

2021-07-09 10:27 UTC, sarroutbi commented
> @sergio-correia @sarroutbi Is there anything I can do to shepherd this process along? It's not so urgent that it must happen now or anything. I just wasn't sure what kind of timeframe I could expect something to happen. It's fine if it takes a while, but it would be helpful to know, even roughly, how long it is likely to take.

Hello @somewhere-or-other. In my opinion, this could be merged, but I would prefer @sergio-correia to review it. As additional suggestion, it would be nice if you could add a unit test for this particular issue.

2023-01-17 21:48 UTC, somewhere-or-other commented
@sergio-correia, @sarroutbi 

I realize it's been a while for this PR, but I'd still love to see it get merged, if possible.  We're starting to see more and more use cases for it, via the related [ClusterLabs PR](https://github.com/ClusterLabs/resource-agents/pull/1656).  I'm happy to re-work it if there's a problem you can identify.

2023-01-18 08:45 UTC, sarroutbi requested changes
Hello. Thanks for your PR. Changes LGTM. However, I miss including the option added to its appropriate manual page.

Could you please document new option in file src/luks/clevis-luks-unlock.1.adoc?

2023-01-18 16:06 UTC, somewhere-or-other commented
@sarroutbi You're absolutely right.  I totally forgot to do that.  Should be there now.

2023-01-27 15:12 UTC, somewhere-or-other commented
Okay.  I'm still reviewing the logs from the build tests to see if I can figure out what went wrong.  It might take me a day or two...

2023-01-28 10:15 UTC, sarroutbi commented
> I'm reviewing the logs from last night's failed build tests. Given that [my test](https://github.com/latchset/clevis/actions/runs/3950634686/jobs/6916671470#step:7:51) seems to have passed, and [another one](https://github.com/latchset/clevis/actions/runs/3950634686/jobs/6916671470#step:7:58) was the one that failed, this seems like a more general problem, either with the code base, or the testing infrastructure.
> 
> If I'm wrong, please let me know, and I'll do my best to fix it.

Let me re-run all the jobs and let's check. I agree this seems more related to testing infrastructure.

2023-01-28 10:24 UTC, sarroutbi commented
@sergio-correia : please, review when possible. Changes LGTM.

2023-02-06 13:58 UTC, sergio-correia approved these changes

2023-02-06 13:58 UTC, merged

2024-03-06 11:11 UTC, mvollmer commented
This is super useful, but I don't see it in any release yet. Is that right?

2024-03-06 11:18 UTC, mvollmer commented
@sarroutbi, @sergio-correia, could we get a release with this, please? So that this will eventually end up in distributions.

2024-03-07 13:07 UTC, sarroutbi commented
Hello @mvollmer . We have some pending PRs that need to be reviewed. Once merged, we will create the new release.

2024-03-08 06:35 UTC, mvollmer commented
> Hello @mvollmer . We have some pending PRs that need to be reviewed. Once merged, we will create the new release.

Thank you!