Fixes Unlocking Multiple boot drives
latchset/clevis pull request #326
Opened 2021-07-12 22:13 UTC by ngtech

Fixes unlocking multiple luks drives in initramfs - similar to those described  in #277  

Without this change  luks1_decrypt & luks2_decrypt functions always return 1.

My understanding is that  the original return 0  statement  refers to / exits the `| while read -r slot state uuid; do`  sub shell and not the function and execution always continues with the return 1 statement.

I choose to return 10 inside the sub shell & check for it outside the sub-shell - to differentiate from the default $? value of 0 if the last command succeeded. Not the most elegant solution but avoids further changes.

2021-07-12 22:27 UTC, ngtech commented
An example script that behaves similarly is

```#!/bin/bash
do_something() {
  cat /etc/fstab | while read -r line; do
      echo "LN: $line"
      echo "inner"
      return 0
  done
  return 2 
}

echo "calling"
do_something
echo "Returned $?"
```
which when called always returns 2

```
$ ./bash_test.sh 
calling
LN: # /etc/fstab: static file system information.
inner
Returned 2
```

2021-11-29 11:07 UTC, sarroutbi requested changes
Please, remove empty whitespaces (lines 75, 107-109)

2021-11-29 11:40 UTC, sarroutbi commented on src/initramfs-tools/scripts/local-top/clevis.in
> +        return 10
Instead of using "10", I would add a readonly constant for the script so that code is more understandable, something like:

readonly DECRYPT_OK=10

... 
    return ${DECRYPT_OK}
    
    if [ $? -eq ${DECRYPT_OK} ];

2022-04-18 06:35 UTC, ngtech commented
As I mentioned in #277 the server that needed those changes to boot has been decomissioned so I am not currently able to verify if this pull request is still needed / works ok. I will try to find some time to set up a test VM.

2024-01-12 09:19 UTC, sarroutbi commented
Hello. It is long since this was opened, so we are closing it. Please, feel free to reopen it if you consider necessary

2024-01-12 09:19 UTC, closed without merging