Include --netrc-file when calling curl
latchset/clevis pull request #402
Opened 2023-01-31 15:10 UTC by sarroutbi

Resolves: #401

Signed-off-by: Sergio Arroutbi <sarroutb@redhat.com>

2023-02-03 17:01 UTC, sergio-correia requested changes
Let's discuss the enhancement before diving into the code, but looking into the PR, I am not a fan of that harcoded `/root/.netrc` -- is this feature only intended to be used by root?

2023-02-06 08:57 UTC, sarroutbi commented
> Let's discuss the enhancement before diving into the code, but looking into the PR, I am not a fan of that harcoded `/root/.netrc` -- is this feature only intended to be used by root?

Well, I don't see many cases where binding is required as "non-root" user, as it normally requires access to a device. But yes, in an ideal case, this should be passed as external argument, I agree with that. I'll try to figure out how to do this, as there is no "clevis configuration file" where this could be configured

2023-05-03 11:28 UTC, sarroutbi commented
> Let's discuss the enhancement before diving into the code, but looking into the PR, I am not a fan of that harcoded `/root/.netrc` -- is this feature only intended to be used by root?

As this is used for encryption and decryption (also at boot time), I suggest using a configuration file under /etc. Change contemplates the possibility of this file not to exist, leaving execution intact (file can not exist, and everything will continue to work similarly)

2025-05-09 16:31 UTC, sarroutbi commented
Unnecessary at this moment

2025-05-09 16:31 UTC, closed without merging