Fix README.md to include tang https configuration (#175)
latchset/clevis pull request #417
Opened 2023-05-23 10:03 UTC by MaxiStarling56

2023-05-29 09:51 UTC, sarroutbi requested changes

2023-05-29 09:51 UTC, sarroutbi commented on README.md
> +If you're using **tang** as pin and the tang server is using tls (Example: `'{"url": "https://tang.remote"}'`), the folder `/etc/ssl` should be included in the initramfs image, `--include /etc/ssl /e
Normally, documentation refers to Tang (not tang) for Tang server. Also, use capital letters (TLS instead of tls) for acronyms.

2023-05-29 13:09 UTC, MaxiStarling56 commented on README.md
> +If you're using **tang** as pin and the tang server is using tls (Example: `'{"url": "https://tang.remote"}'`), the folder `/etc/ssl` should be included in the initramfs image, `--include /etc/ssl /e
So, it should be like the following?
```Markdown
If you're using **Tang** with TLS (Example: `'{"url": "https://tang.remote"}'`), the folder `/etc/ssl` should be included in the initramfs image, `--include /etc/ssl /etc/ssl --force` when creating with dracut.
```

Thanks for the feedback

2023-05-29 13:28 UTC, sergio-correia commented on README.md
> +If you're using **tang** as pin and the tang server is using tls (Example: `'{"url": "https://tang.remote"}'`), the folder `/etc/ssl` should be included in the initramfs image, `--include /etc/ssl /e
It might be better to change the dracut/initramfs-tools modules to include the required certificates, so that it would work with HTTPS out of the box.

2023-05-29 13:57 UTC, MaxiStarling56 commented on README.md
> +If you're using **tang** as pin and the tang server is using tls (Example: `'{"url": "https://tang.remote"}'`), the folder `/etc/ssl` should be included in the initramfs image, `--include /etc/ssl /e
> It might be better to change the dracut/initramfs-tools modules to include the required certificates, so that it would work with HTTPS out of the box.

Tried that but wasn't able to, I'm not very good on linux but will try again, anyway I think that while there isn't a better solution the readme shoud at least inform the users  that there is this workaround.

2024-01-18 11:12 UTC, sarroutbi commented on README.md
> +If you're using **Tang** with TLS (Example: `'{"url": "https://tang.remote"}'`), the folder `/etc/ssl` should be included in the initramfs image, `--include /etc/ssl /etc/ssl --force` when creating w
When specifying this:
```
--include /etc/ssl /etc/ssl --force
```
Is it necessary to provide `/etc/ssl` twice?

2024-01-18 11:19 UTC, MaxiStarling56 commented on README.md
> +If you're using **Tang** with TLS (Example: `'{"url": "https://tang.remote"}'`), the folder `/etc/ssl` should be included in the initramfs image, `--include /etc/ssl /etc/ssl --force` when creating w
Yes, the first is "_where to copy the files from?_", the second is "_where to put it in the builded initramfs image?_", more info [here](https://linuxconfig.org/how-to-build-an-initramfs-using-dracut-on-linux), in the section "Including extra files in the initramfs with the --include option"

2024-05-06 14:47 UTC, sarroutbi approved these changes
Change LGTM

2024-05-09 10:07 UTC, sergio-correia approved these changes

2024-05-09 10:35 UTC, merged