Added language and misspell check for markdown files
latchset/clevis pull request #439
Opened 2023-09-07 13:05 UTC by yo-404

## Resolves #407

### Description

Changes proposed in this pull request:

- Added Language Tool
- Added Misspell check

Files Added

    spellcheck.yaml @.github\workflows\

### results
![image](https://github.com/latchset/clevis/assets/100558220/cd46047a-020b-4884-842b-593492e9a7d7)

![image](https://github.com/latchset/clevis/assets/100558220/15c4c62a-33a0-4f09-aa7a-3ae357863a76)

![image](https://github.com/latchset/clevis/assets/100558220/b57e98f8-3966-4737-ad94-86dfcc80a557)

currently level is set to `warning` so that it doesnt stops the PR and CI will succeed with info shown as warning . Can be changed to `error` if required

2024-01-15 11:12 UTC, sarroutbi requested changes

2024-01-15 11:12 UTC, sarroutbi commented on .github/workflows/spellcheck.yml
> +  push:
Could you please include it for pull requests?:

```
on:
  push:
    branches: ["main"]
  pull_request:
```

2024-01-15 11:38 UTC, yo-404 commented on .github/workflows/spellcheck.yml
> +  push:
sure

2024-01-15 12:06 UTC, yo-404 reviewed
Added pull_request

2024-01-18 10:46 UTC, sarroutbi approved these changes
Change LGTM

2024-01-18 10:54 UTC, merged