[WIP] Add TPM 1.2 support
latchset/clevis pull request #462
Opened 2024-05-05 21:34 UTC by oldium

This patch series adds TPM 1.2 series. This is a work-in-progress and will take some time (days/weeks, depends on my free time).

Status:

 * [✅ Done] Clevis encrypt, decrypt, bind support
 * [✅ Done] initramfs-tools support
 * [✅ Done] Systemd support
 * [✅ Done] Manual page for `clevis-encrypt-tpm1`
 * [✅ Done] Tests for tpm1 pin
 * [💫 Investigating] Dracut support

Example usage:

 * Boot and unlock with TPM1.2:
     `clevis luks bind -d /dev/<device> tpm1 '{"pcr_ids":"0,4,7"}'`
 * Encrypt and decrypt:
     `echo test | clevis encrypt tpm1 '{"pcr_ids":"0,4,7"}' | clevis decrypt`

Fixes: #84

2024-06-30 16:54 UTC, oldium commented
Work is done, pre-built packages for Debian 12 and amd64 arch are available here https://github.com/oldium/clevis/releases/tag/v20_tpm1

2024-07-03 07:49 UTC, oldium commented
The CentOS test build image needs some love, the mirrorlist.centos.org site does not exist any more it seems. 
![image](https://github.com/latchset/clevis/assets/1260936/ce031b8a-8f97-4298-b69f-ce1413b759d7)

2024-07-03 20:48 UTC, oldium commented
Rebased to latest master to fix the build.

2024-07-03 21:00 UTC, oldium commented
The build failure is caused by some hashes mismatch in centos:stream9, but when run locally with https://github.com/nektos/act, it works. Probably a temporary issue.

2024-09-27 12:17 UTC, oldium commented
I will rebase the Pull Request and check if there is any update to clevis_luks_used_pins function necessary towards the new pkcs11 feature.

2024-09-28 21:42 UTC, oldium commented
Rebased, manually pre-built packages (including pkcs11, untested) for Debian 12 and amd64 arch are available here https://github.com/oldium/clevis/releases/tag/v21_tpm1

I see that the pkcs11 tests use software emulation, so this is an inspiration for me to do the same with TPM 1 😁 (and maybe I can improve TPM 2 test as well) - I will try to do the same with `swtpm`.

For Debian, I added small patch to allow installation of pkcs11 files for dracut without actually the need to have pkcs11 pin installed, same as it is done for TPM1 and TPM2:

```patch
diff --git a/src/luks/dracut/clevis-pin-pkcs11/module-setup.sh.in b/src/luks/dracut/clevis-pin-pkcs11/module-setup.sh.in
index 39d06a0..4abac0f 100755
--- a/src/luks/dracut/clevis-pin-pkcs11/module-setup.sh.in
+++ b/src/luks/dracut/clevis-pin-pkcs11/module-setup.sh.in
@@ -17,6 +17,12 @@
 #
 # shellcheck disable=SC2154
 #
+
+check() {
+    require_binaries pcscd pkcs11-tool socat clevis-decrypt-pkcs11 || return 1
+    return 0
+}
+
 depends() {
     echo clevis
     return 255
-- 
```

2024-09-28 21:54 UTC, oldium commented
I added the patch as a separate Pull Request #480

2024-09-29 11:47 UTC, natterangell commented
This is amazing work, @oldium! I sincerely hope this can be merged, as it makes it possible for my older thinkpads to utilize TPM 1.2 for LUKS unlocking in conjuction with coreboot/edk2, secure boot and unified kernel images. That's a very decent secure boot path up until logging in to the system.

I'll try to build this manually for void linux too.

2024-09-30 10:54 UTC, oldium commented
Finally, I was able to get SW emulation working (with `swtpm` package), some custom `tcsd` `LD_PRELOAD` love was necessary to force it start during CI build, but nothing unsolvable 😅.

2024-09-30 20:48 UTC, oldium commented
I just figured out that the CI is not updated to have the needed libraries, I will do it in the following days.

2024-10-02 10:17 UTC, oldium commented
Finished work on tests, now it works on all build targets.

Observed issues:

* `swtpm` sometimes does not stop on Fedora, so needs to be killed
* `swtpm` does not support TPM 1.2 on CentOS Stream 9+ [intentionally](https://bugzilla.redhat.com/show_bug.cgi?id=1990153), which is a pity, so tests are skipped there
* CentOS Stream 10 does not have EPEL repository released yet (they are working on it)

2024-10-02 14:21 UTC, oldium commented
It should be possible to add TPM 2 SW emulation support for tests rather easily I think.

2024-10-03 10:34 UTC, oldium commented
I got a feeling that this Pull Request is now ready with all the features it should have.

2024-10-03 10:41 UTC, natterangell commented
Any chance you can release a Fedora 40 RPM for this fork like you did for Debian 12? I'd love to pull that into a custom ublue image.

2024-10-03 19:25 UTC, oldium commented
> Any chance you can release a Fedora 40 RPM for this fork like you did for Debian 12? I'd love to pull that into a custom ublue image.

Yep, that should be possible. I will have a look at it during the weekend.

2024-10-03 22:13 UTC, oldium commented
There is one incompatible change in `libdl.so`/`libdl.so.2` in recent distros, I need to check that.

2024-10-06 11:46 UTC, oldium commented
I was able to create Fedora package successfully, but I am not convinced about the approach Fedora packaging chose, because it contains dependency to both tpm1 and tpm2 (tpm-tools, trousers, tpm2-tools). The Debian packaging is more granular, so you just install what you need, either tpm1 or tpm2. I need to test it later today/tomorrow, I created a new VM with Fedora 40 for that.

2024-10-06 22:44 UTC, oldium commented
Latest Debian 11 (bullseye), 12 (bookworm) and Fedora v39, v40 and v41 packages are available here https://github.com/oldium/clevis/releases/tag/v21_tpm1u2.

2024-10-08 14:49 UTC, sarroutbi commented
> @sarroutbi I think it would be good to split first 5 commits into separate Pull Requests. They are rather independent improvements/fixes (including fix for #456), so they can be handled more easily. Right?

I don't consider it necessary. It is a pretty big PR, I agree, but we will create a new release (hopefully v22.0) once PKCS#11 status is stable and this TPM1.2 is included.

@sergio-correia : any thoughts?

2024-10-08 18:11 UTC, oldium commented
Ok, thanks. Please do not hesitate to tell me if you wish to split it or do anything else, it is Git after all, so anything can be done 😊

2024-10-08 18:51 UTC, natterangell commented
Just a quick confirmation this works great also with a Thinkpad X230 and Fedora 40. Haven’t been able to make it work on ublue/bluefin yet but they have an unusual Dracut generation process, so I’ll dig more on that.

2024-10-09 00:29 UTC, oldium commented
> Just a quick confirmation this works great also with a Thinkpad X230 and Fedora 40. Haven’t been able to make it work on ublue/bluefin yet but they have an unusual Dracut generation process, so I’ll dig more on that.

Great, thanks for testing. I have never heard of Bluefin, but it looks like a Fedora clone. If I am able to make a VM from the installation media, count with me 😊 I will check it later this week.

2024-10-09 12:52 UTC, oldium commented
@natterangell Which release of Bluefin are you most interested in? GTS (Fedora 39) or stable (Fedora 40)?

2024-10-09 15:00 UTC, oldium commented
I think I got it. Fedora is using `hostonly=yes` Dracut config, while Ublue-OS has `hostonly=no`. The Fedora's RPM unfortunately does not contain required file trouser's `syste.data.auth`, so I will probably need to provide a fallback copy in Clevis.

2024-10-09 15:51 UTC, natterangell commented
I’m building a Bluefin Stable (40) image over here: https://github.com/natterangell/bluefin-dx-thinkpad

I’m basically force replacing clevis and clevis-luks, then adding clevis-dracut and clevis-systemd (all from your fork). 

Yes, I’ve noticed the system.data.auth missing. Can that just be dropped in? 

When I run lsinitramfs on the locally generated one (which must be manually done with ‘rpm-ostree initramfs —enable’ it seems to include clevis and everything needed for tpm2, but not tpm1 (let me know if want grep-files).

is system.data.auth enough?

2024-10-09 16:30 UTC, oldium commented
> I’m building a Bluefin Stable (40) image over here: https://github.com/natterangell/bluefin-dx-thinkpad
> 
> I’m basically force replacing clevis and clevis-luks, then adding clevis-dracut and clevis-systemd (all from your fork).

I used `rpm-ostree install` as an alternative to `dnf install` as written in Fedora 40 steps in my release. I first ran `dnf install`, this failed, second run with `rpm-ostree install` succeeded. Then I rebooted. In this way I had clevis from RPMs installed.

> Yes, I’ve noticed the system.data.auth missing. Can that just be dropped in?
>
> When I run lsinitramfs on the locally generated one (which must be manually done with ‘rpm-ostree initramfs —enable’ it seems to include clevis and everything needed for tpm2, but not tpm1 (let me know if want grep-files).

Here I need to provide an error message, it just checks for file existence and returns 1 to skip it - Dracut itself does not print anything unfortunatelly.

> is system.data.auth enough?

Yes, just put it as `/usr/share/trousers/system.data.auth` or `/var/lib/tpm/system.data.auth` and re-run `rpm-ostree initramfs --enable`.

> Vanilla Fedora 40 works great with your fork! The problem is Bluefin is container based, its downstream of Fedora Silverblue, so it ships initramfs prebuilt, so to speak.

2024-10-09 21:28 UTC, oldium commented
Fixed in update 3 at https://github.com/oldium/clevis/releases/tag/v21_tpm1u3. `rpm-ostree` is weird. No more 😅

2024-10-10 14:18 UTC, oldium commented
Ha! It is possible to reinstall clevis in single run by issuing `rpm-ostree install ./clevis-21-1.tpm1u3.fc40.x86_64.rpm ./clevis-dracut-21-1.tpm1u3.fc40.x86_64.rpm ./clevis-luks-21-1.tpm1u3.fc40.x86_64.rpm ./clevis-systemd-21-1.tpm1u3.fc40.x86_64.rpm --uninstall clevis --uninstall clevis-dracut --uninstall clevis-luks --uninstall clevis-systemd`. But the package management in this way is painfully slow...

2024-10-22 21:42 UTC, mauro2306 commented
Hi there, i am trying to install and use your update 3 package of Clevis 21 for TPM 1.2 but i am running in issues to get it working. 
I tried the following : 
- Reset multiple times the TPM and secure boot
- use long passwords without special characters
- use shorter passwords without special characters
and nothing to do, i always fail when trying to bind my tpm device to my LUKS volume : 
`sudo clevis-luks-bind -d /dev/sda3 tpm1 '{"pcr_ids":"0,4,7"}'
Enter existing LUKS password: 
Tspi_Key_CreateKey failed: 0x00000001 - layer=tpm, code=0001 (1), Authentication failed
Unable to seal jwk
Unable to perform encryption with PIN 'tpm1' and config '{"pcr_ids":"0,4,7"}'
Error adding new binding to /dev/sda3
`
I am sure the password for the TPM is the good one, as if i try to set or read stuff with any tpm** command, it works.

I am using Ubuntu 24.10 with Systemd, TPM1.2 of a Sony Vaio laptop, and tried multiple pcr_ids just to be sure (only 0, 4 or 7). I don't know if it makes a difference, but my volume is a LUKSv2 one. Hope to get some help, let me know if you need any additional information.

2024-10-23 05:40 UTC, natterangell commented
@mauro2306, try to clear your tpm, then take ownership with the following command `tpm_takeownership -z`. Then try binding again.

2024-10-23 05:43 UTC, mauro2306 commented
> @mauro2306, try to clear your tpm, then take ownership with the following command `tpm_takeownership -z`. Then try binding again.

I tried that one, failed with the error that "SRK was not set". Let me quickly do it again

2024-10-23 13:55 UTC, oldium commented
@mauro2306

Yes, `tpm_takeownership -z` sets SRK to the _well-known_ value (i.e. all hex 0x00), this is expected by Clevis implementation. There is a possibility to _change_ SRK to _well-known_ value (when you own TPM already) with `tpm_changeownerauth --srk --set-well-known` (there is a typo in documentation in this PR, I need to fix it).

You are binding with PCRs 0, 4 and 7. Try binding first without any PCRs `clevis luks bind -d /dev/sda3 tpm1 '{}'` to verify whether it actually works. Afterwards, unbind and bind again with PCR 0 and continue next boot by adding another value. One of my Linux boxes is able to boot with PCRs 0,2,7, but second one with 0,4,7 (I am booting into custom-signed kernel directly from EFI shell). It depends on the BIOS implementation.

2024-10-25 15:38 UTC, mauro2306 commented
> @mauro2306
> 
> Yes, `tpm_takeownership -z` sets SRK to the _well-known_ value (i.e. all hex 0x00), this is expected by Clevis implementation. There is a possibility to _change_ SRK to _well-known_ value (when you own TPM already) with `tpm_changeownerauth --srk --set-well-known` (there is a typo in documentation in this PR, I need to fix it).
> 
> You are binding with PCRs 0, 4 and 7. Try binding first without any PCRs `clevis luks bind -d /dev/sda3 tpm1 '{}'` to verify whether it actually works. Afterwards, unbind and bind again with PCR 0 and continue next boot by adding another value. One of my Linux boxes is able to boot with PCRs 0,2,7, but second one with 0,4,7 (I am booting into custom-signed kernel directly from EFI shell, so for me PCR7 is crucial). It depends on the BIOS implementation.

Thanks for the help, i tried without anything, and still not auto-unlocking my partition at boot. I waited 2minutes just to be sure. I have no errors while binding the luks partition with clevis at all to the tpm, this looks good. Maybe i am missing a GRUB module ? I will continue to dig and report.

2024-10-26 07:04 UTC, mauro2306 commented
I tried pretty much everything i could find on the internet, and i am not succeeding in auto-unlocking my luks partition at boot using my tpm 1.2 device.
Some reports from the command i tried : 
```
sudo cryptsetup luksDump /dev/sda3
LUKS header information
Version:        2
Epoch:          29
Metadata area:  16384 [bytes]
Keyslots area:  16744448 [bytes]
UUID:           db0d5008-e645-4106-a96b-7b427ab1d1d3
Label:          (no label)
Subsystem:      (no subsystem)
Flags:          (no flags)

Data segments:
  0: crypt
        offset: 16777216 [bytes]
        length: (whole device)
        cipher: aes-xts-plain64
        sector: 512 [bytes]

Keyslots:
  0: luks2
        Key:        512 bits
        Priority:   normal
        Cipher:     aes-xts-plain64
        Cipher key: 512 bits
        PBKDF:      argon2id
        Time cost:  4
        Memory:     628564
        Threads:    4
        Salt:       39 dc 2c 19 c5 fb 41 ff 20 b1 26 b7 fc ae 0b b1 
                    59 af b6 55 4f b1 f1 9c 3e cf ac 7c f3 2e 08 f1 
        AF stripes: 4000
        AF hash:    sha256
        Area offset:32768 [bytes]
        Area length:258048 [bytes]
        Digest ID:  0
  1: luks2
        Key:        512 bits
        Priority:   normal
        Cipher:     aes-xts-plain64
        Cipher key: 512 bits
        PBKDF:      pbkdf2
        Hash:       sha256
        Iterations: 1000
        Salt:       63 25 c6 bf 31 11 a3 f9 90 cc 35 d5 5b 4f 31 49 
                    96 45 44 eb 82 1f 64 0f 23 f9 c2 17 cb 64 45 b2 
        AF stripes: 4000
        AF hash:    sha256
        Area offset:290816 [bytes]
        Area length:258048 [bytes]
        Digest ID:  0
Tokens:
  0: clevis
        Keyslot:    1
Digests:
  0: pbkdf2
        Hash:       sha256
        Iterations: 84344
        Salt:       03 a8 c6 1d ad 62 ab e1 18 42 b9 32 ca 0c 3a cb 
                    b4 97 7d d4 eb 8b 92 55 56 44 2d 6a ad 09 4e 59 
        Digest:     94 97 7d 86 59 ec 0a db a2 d1 c4 da 75 bd 69 6f 
                    22 ac 1e 01 02 c5 c3 10 b3 9d e4 c7 ee cf c8 16 

```
sudo cat /sys/class/tpm/tpm0/device/pcrs
PCR-00: 71 F8 B2 A7 A5 2D D8 AF 14 EA 9F E3 AA 6A B5 68 6A 11 3E 47 
PCR-01: 9F F4 D4 B1 93 55 E8 E8 03 47 7A 34 91 2A F8 22 C0 E6 DA 65 
PCR-02: 15 6E A7 5F 20 15 67 F6 E0 75 4D 71 79 40 3D 4D 9E 2F 32 CF 
PCR-03: B2 A8 3B 0E BF 2F 83 74 29 9A 5B 2B DF C3 1E A9 55 AD 72 36 
PCR-04: D0 51 F5 32 50 CC B4 CE AF F9 3E 15 27 C5 13 96 BF 52 34 86 
PCR-05: DC A3 10 B0 BC F1 96 CC B0 15 C7 02 D2 16 6D 20 91 51 AB B7 
PCR-06: 90 20 EB AC 21 CE BA 8A C0 AB 92 0E D9 27 E4 F8 91 C9 03 D8 
PCR-07: 3B 84 95 50 1C 5E 7E 2D F2 22 F9 5B 65 26 2D 01 76 2E 28 24 
PCR-08: BF E2 A8 1C C3 8D 22 A0 84 67 6C B9 96 A9 E1 AA 9E A5 85 DE 
PCR-09: EC 33 21 C6 95 3D 59 F6 3D 8B 4B FE 3F BE EE 47 60 C8 74 0F 
PCR-10: 29 14 26 E4 8A B0 31 4B 82 A0 D8 73 34 69 2A 68 5B E9 7D 91 
PCR-11: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
PCR-12: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
PCR-13: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
PCR-14: A4 82 A1 5E 11 27 17 D6 A9 15 B9 89 A0 EA 61 40 A5 07 E3 E6 
PCR-15: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
PCR-16: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
PCR-17: FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
PCR-18: FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
PCR-19: FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
PCR-20: FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
PCR-21: FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
PCR-22: FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
PCR-23: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 


I don't see where the problem is. Using Kubuntu 24.10, apparently with systemd. 
```
```

2024-10-26 18:21 UTC, oldium commented
Lets do some tests to check where the problem is (run everything as root). Please check whether locking and unlocking via TPM works:

```bash
$ echo Test | clevis encrypt tpm1 '{}' | clevis decrypt
Test
```

```bash
$ echo Test | clevis encrypt tpm1 '{"pcr_ids":"0,4,7"}' | clevis decrypt
Test
```

Next check if unlocking after `clevis luks bind` works. First list all slots (shown `tpm1` parameters may vary) and then test if the slot can be unlocked (use corresponding number in `-t <number>` parameter)

```bash
$ clevis luks list -d /dev/sda3
1: tpm1 '{"pcr_ids":""}'
```

```bash
$ clevis luks unlock -d /dev/sda3 -t 1 && echo "Works"
Works
```

If you see `Test for token slot 1 on device /dev/sda3 failed.`, you have problem with TPM and we can try to reset it. Otherwise, you have problem during boot, which means phase immediately _after_ Grub. The unlocking does not happen in Grub, but in initramfs or Dracut.

I read that Ubuntu 24.10 started using [Dracut](https://www.phoronix.com/news/Ubuntu-Considers-Dracut-Initrd), so I will test it there if there isn't any suspicious difference from Debian or RedHat. For Dracut you can find logs via `journalctl -b`.

2024-10-26 19:43 UTC, mauro2306 commented
> Lets do some tests to check where the problem is (run everything as root). Please check whether locking and unlocking via TPM works:
> 
> ```shell
> $ echo Test | clevis encrypt tpm1 '{}' | clevis decrypt
> Test
> ```
> 
> ```shell
> $ echo Test | clevis encrypt tpm1 '{"pcr_ids":"0,4,7"}' | clevis decrypt
> Test
> ```
> 
> Next check if unlocking after `clevis luks bind` works. First list all slots (shown `tpm1` parameters may vary) and then test if the slot can be unlocked (use corresponding number in `-t <number>` parameter)
> 
> ```shell
> $ clevis luks list -d /dev/sda3
> 1: tpm1 '{"pcr_ids":""}'
> ```
> 
> ```shell
> $ clevis luks unlock -d /dev/sda3 -t 1 && echo "Works"
> Works
> ```
> 
> If you see `Test for token slot 1 on device /dev/sda3 failed.`, you have problem with TPM and we can try to reset it. Otherwise, you have problem during boot, which means phase immediately _after_ Grub. The unlocking does not happen in Grub, but in initramfs or Dracut.
> 
> I read that Ubuntu 24.10 started using [Dracut](https://www.phoronix.com/news/Ubuntu-Considers-Dracut-Initrd), so I will test it there if there isn't any suspicious difference from Debian or RedHat. For Dracut you can find logs via `journalctl -b`.

Hi there,
thanks for the support. I tried again to unbind and bind, without PCRs, with 0 and 7, all looks good from the commands you asked me to enter. However, i am using Kubuntu, not Ubuntu, and it looks like i am on Systemd by default according to the below : 

``
mauro@mauro-svs1312s9eb:~$ sudo echo Test | clevis encrypt tpm1 '{"pcr_ids":"0,7"}' | clevis decrypt
Test
mauro@mauro-svs1312s9eb:~$ sudo clevis luks unlock -d /dev/sda3 -t 1 && echo "Works"
Works
mauro@mauro-svs1312s9eb:~$ sudo clevis luks list -d /dev/sda3
1: tpm1 '{"pcr_ids":"0,7"}'
mauro@mauro-svs1312s9eb:~$ ps -p 1 -o comm=
systemd
``

2024-10-26 20:37 UTC, oldium commented
Perfect, so it looks like the only issue is booting. I will check Ubuntu 24.10 (already installing), maybe also Kubuntu, if it boots fine. It seems you are using default disk layout (/dev/sda1 on /boot/efi, /dev/sda2 on /boot and /dev/sda3 is crypted root), so I should be able to reproduce what you see. If not, we will check `journalctl -b` together.

2024-10-26 21:03 UTC, oldium commented
Ha! I see that initramfs built-in Busybox `ps -A` is not supported on Ubuntu 24.10, even `ps -o pid,ppid` does not work. So `clevis` is currently out-of-the-game (both versions are used internally). We will need to do some awk sorcery to make this working I wonder...

Broken:

* get_askpass_info - uses `ps -A`, which does not work (just try `/usr/lib/initramfs-tools/bin/busybox ps -A`)
* process clean-up after unlocking - uses `ps -o pid,ppid`, which does not work too

Well...

2024-10-26 21:05 UTC, oldium commented
Nothing that cannot be fixed, though 😁 It depends on my free time, but I think I can provide a fix during the next week.

2024-10-26 21:09 UTC, oldium commented
Please confirm that you are using `clevis-initramfs` package and not `clevis-dracut` one (just to be sure if there isn't anything more to be fixed). Thanks.

2024-10-26 21:17 UTC, mauro2306 commented
> Nothing that cannot be fixed, though 😁 It depends on my free time, but I think I can provide a fix during the next week.

Ok thanks, nothing urgent anyway. I will have to dig a bit in what is busybox and all of that, i mean, i know the name for sure, but i want to be more familiar with it.  For example, i never eared of dracut before starting to try to play with clevis. I will try to find some easy documentation and we will see. About your last question, yes, i was using your systemd modified version of clevistpm1.2u3 no worries.
Here is the list of clevis packages installed on my machine :
clevis            
clevis-initramfs  
clevis-luks       
clevis-systemd    
clevis-tpm1

All coming from this page : https://github.com/oldium/clevis/releases/tag/v21_tpm1u3

2024-11-02 07:36 UTC, mauro2306 commented
> Small update - I have prepared the fix, I just need to test it in all scenarios (initramfs, Dracut, Dracut w/o systemd). Stay tuned 😊

Awesome, thanks, ready to test :-)

2024-11-03 19:52 UTC, oldium commented
Finished testing (Fedora 40 Dracut, Bluefin stable Dracut, Debian 12 initramfs-tools/Dracut, Ubuntu 24.10 initramfs-tools), enjoy 😊.

https://github.com/oldium/clevis/releases/tag/v21_tpm1u4

2024-11-03 20:02 UTC, oldium commented
Note: This PR incorporates #496 (in commit _dracut: supply cryptsetup password through pipe in Dracut_, which introduces common killing function for initramfs-tools and Dracut w/o SystemD). If #496 is merged first, I can easily update this PR, because this is exactly my building branch https://github.com/oldium/clevis/tree/feature/tpm1_build.

Otherwise, there is no end-result difference between my `feature/tpm1` (with incorporated #496) and `feature/tpm1_build` (with separate #496 commit) branches.

2024-11-06 21:28 UTC, mauro2306 commented
Hi there, hope all is going well ? Just tried with update 4, and unfortunately still not working on my side :-(. The results of the command are the same, all seems to be well configured, let me know what you want me to test.

2024-11-07 20:22 UTC, oldium commented
> ```
> mauro@mauro-svs1312s9eb:$ sudo echo Test | clevis encrypt tpm1 '{"pcr_ids":"0,7"}' | clevis decrypt
> Faites glisser votre doigt sur le lecteur d’empreintes
> Test

This command is actually ran as your normal user, only `echo Test` is run as root. But also on my VMs encrypt and decrypt runs without running root, so this is fine. I guess the _Faites glisser votre doigt sur le lecteur d’empreintes_ message is related to `sudo`, right?

> mauro@mauro-svs1312s9eb:$ sudo clevis luks unlock -d /dev/sda3 -t 1 && echo "Works"
> Works
> mauro@mauro-svs1312s9eb:$ sudo clevis luks list -d /dev/sda3
> 1: tpm1 '{"pcr_ids":"0,7"}'
> mauro@mauro-svs1312s9eb:$ ps -p 1 -o comm=
> systemd
> ```

Fine. Let's look into the boot process. Please ensure that you have in `/etc/default/grub`:

```
GRUB_CMDLINE_LINUX_DEFAULT="debug"
```

(or add `debug` separated by space like `"splash debug"` to existing value) and run `sudo update-grub2` and reboot. After the boot you will find `/run/initramfs/initramfs.debug` file, so find it, check whether it contains any sensitive information (should not) and post it here (rename it to `initramfs.debug.txt` and you can drag-drop it to GitHub markdown directly).

2024-11-07 21:21 UTC, oldium commented
Looks like Kubuntu with splashscreen (plymouth) does not want to unlock. Investigating...

2024-11-07 22:03 UTC, oldium commented
This will not be easy, the application crashes in initramfs environment...
![image](https://github.com/user-attachments/assets/bb42156a-b734-41a3-875e-b0fc5f7d93aa)

2024-11-07 22:31 UTC, oldium commented
Ha! Solved. Permission issues:

1. Created `/etc/hosts` is not readable by user (tcsd uses tss user for running) - message `TCSD Could not retrieve client address info`
2. /usr/lib/x86_64-linux-gnu not readable - `libgcc_s.so.1 must be installed for pthread_exit to work` error

2024-11-08 07:38 UTC, RadxaYuntian commented
Created by calamares (the OS installer) by [default](https://github.com/calamares/calamares/blob/calamares/src/modules/initramfs/InitramfsJob.cpp#L87). This might affect other systems as well.

2024-11-08 09:15 UTC, oldium commented
The Calamares change renders the generated initrd filesystem unusable for anything that is not run under root. Their intention was to create a /boot/* files as root-only readable (to prevent reading it by normal users), but it changes how the files are created _inside_ the initrd filesystem. For reference, their bug report: https://github.com/calamares/calamares/issues/1191

2024-11-08 09:59 UTC, oldium commented
Reported to Calamares https://github.com/calamares/calamares/issues/2394

2024-11-09 01:00 UTC, oldium commented
Prepared workaround (run `tcsd` as root and listen on localhost only), will release after testing.

2024-11-09 05:58 UTC, mauro2306 commented
Hi there, sorry i couldn't follow up yesterday, busy day. What do you suggest me, remove the calamares file and generate initramfs files again, or wait for your fix ? I am assuming (dumb assumption) that the reason for this root only permission on boot files is because the boot partition isn't encrypted on Kubuntu but a clear partition ? The default Kubuntu partition scheme when you ask for disk encryption is : 
/boot/efi : fat32 not encrypted of 300MiB
/boot : ext4 not encrypted of 4GiB
/ : ext4 of whatever left

2024-11-09 06:09 UTC, mauro2306 commented
Just as a side note, i quickly tried with deleting the file you mentioned and doing a update-initramfs suggested, and it was still not working. Unbinding clevis from the partition, binding it again and regenerating grub + initramfs worked. Not sure which of the steps help to be honest, but at least now it is working. Will continue to monitor the thread and try to help until the PR makes its way into the official clevis delivery :+1:

2024-11-09 11:50 UTC, oldium commented
> Just as a side note, i quickly tried with deleting the file you mentioned and doing a update-initramfs suggested, and it was still not working. Unbinding clevis from the partition, binding it again and regenerating grub + initramfs worked.

Strange, this should work on the first try. But good that you got it working 👍

2024-11-09 11:52 UTC, oldium commented
I have prepared new release with all the fixes/workarounds and the latest Clevis code:

https://github.com/oldium/clevis/releases/tag/v21_tpm1u5

Tested on Fedora 40 Dracut, Bluefin stable Dracut, Debian 12 initramfs-tools/Dracut, Ubuntu 24.10 initramfs-tools, Kubuntu 24.10 initramfs-tools.

Enjoy 😁

2024-11-09 18:52 UTC, oldium commented
Added Ubuntu 24.10 and 24.04 packages to v21_tpm1u5 release 😊

2024-11-09 19:48 UTC, mauro2306 commented
> I have prepared new release with all the fixes/workarounds and the latest Clevis code:
> 
> https://github.com/oldium/clevis/releases/tag/v21_tpm1u5
> 
> Tested on Fedora 40 Dracut, Bluefin stable Dracut, Debian 12 initramfs-tools/Dracut, Ubuntu 24.10 initramfs-tools, Kubuntu 24.10 initramfs-tools.
> 
> Enjoy 😁

Great, i will be testing this tomorrow probably. Do you want me to restore the initramfs file i deleted to go back to the original Kubuntu state and double check your update5 works in this conditio?

2024-11-09 20:55 UTC, oldium commented
> > I have prepared new release with all the fixes/workarounds and the latest Clevis code:
> > https://github.com/oldium/clevis/releases/tag/v21_tpm1u5
> > Tested on Fedora 40 Dracut, Bluefin stable Dracut, Debian 12 initramfs-tools/Dracut, Ubuntu 24.10 initramfs-tools, Kubuntu 24.10 initramfs-tools.
> > Enjoy 😁
> 
> Great, i will be testing this tomorrow probably. Do you want me to restore the initramfs file i deleted to go back to the original Kubuntu state and double check your update5 works in this conditio?

Yes please, getting back to the original state is good anyway.

2024-11-10 19:22 UTC, mauro2306 commented
> > > I have prepared new release with all the fixes/workarounds and the latest Clevis code:
> > > https://github.com/oldium/clevis/releases/tag/v21_tpm1u5
> > > Tested on Fedora 40 Dracut, Bluefin stable Dracut, Debian 12 initramfs-tools/Dracut, Ubuntu 24.10 initramfs-tools, Kubuntu 24.10 initramfs-tools.
> > > Enjoy 😁
> > 
> > 
> > Great, i will be testing this tomorrow probably. Do you want me to restore the initramfs file i deleted to go back to the original Kubuntu state and double check your update5 works in this conditio?
> 
> Yes please, getting back to the original state is good anyway.

Done, all working fine with update5 and restoring the file and generating initramfs back with the file in. Thanks for the help i am really glad that i can run FDE using my tpm1.2, this is really great. The holy grail now would be to not get the prompt if tpm drecrypts successfully the partition and only get it in case there is an issue with it or secure boot, but of course that's only cosmetic and UX, the feature works at least which is the most important :+1:

2024-11-11 21:25 UTC, oldium commented
> The holy grail now would be to not get the prompt if tpm drecrypts successfully the partition and only get it in case there is an issue with it or secure boot, but of course that's only cosmetic and UX, the feature works at least which is the most important 👍

That would require a different approach, because basically what Clevis does is reply to a password prompt. It does not actually unlock the partition.

2024-11-14 18:37 UTC, akostadinov commented
Great work! I'm just building a server and it turned out it only has TPM 1.2. But I wanted to use clevis with TPM+tang.

Who has to review this to get it included?

Also are there any instructions how to initialize the TPM? I ran `tpm_takeownership` and set an owner and skr password. But then I get:

```
$ sudo clevis luks bind -d /dev/sda8 tpm1 '{"pcr_ids":"0,1"}'
Enter existing LUKS password: 
Tspi_Key_CreateKey failed: 0x00000001 - layer=tpm, code=0001 (1), Authentication failed
Unable to seal jwk
Unable to perform encryption with PIN 'tpm1' and config '{"pcr_ids":"0,1"}'
Error adding new binding to /dev/sda8
```

2024-11-14 18:54 UTC, akostadinov commented on README.md
> +`tpm_changeownerauth --srk --well-known` has been called to change it. Please
```suggestion
`tpm_changeownerauth --srk --set-well-known` has been called to change it. Please
```

For me your command asked me for a new password. With the above command, I was asked about the owner password only and it set the srk automatically. Now setting the pin works.

2024-11-14 18:58 UTC, mauro2306 commented on README.md
> +`tpm_changeownerauth --srk --well-known` has been called to change it. Please
If you look to everything I tried above, you will see that I had the same issue and the solution was to perform the command with "-k" when taking ownership to fill in with 0 the above unused PCRs and it worked fine for me

2024-11-14 19:38 UTC, oldium commented on README.md
> +`tpm_changeownerauth --srk --well-known` has been called to change it. Please
Sorry, I forgot about this one. It should be `--set-well-known`, I wrote about it earlier.

2024-11-14 19:49 UTC, oldium commented on README.md
> +`tpm_changeownerauth --srk --well-known` has been called to change it. Please
Will fix ASAP

2024-11-14 19:57 UTC, oldium commented
@akostadinov TCSD is added by `clevis-pin-tpm1`, so you will not see `tcsd` in Dracut output (there is nothing like that in Dracut, I guess it is too ancient for anybody to modify that package). I will add Fedora 41 to my testbench to check if there is anything wrong... Do you use Plymouth (`splash` in Grub kernel parameters) or not?

2024-11-14 20:54 UTC, oldium commented
I just tested Fedora 41 Server install (no splash screen) and unlocking works fine with tpm1u5 version (I had to correct Fedora 41 installation instructions, it contained fc40 install packages). Clevis boots just fine with default Fedora settings and `takeownership -z`, `clevis luks bind -d /dev/vda3 tpm1 '{}'`, `dracut -f -v` and `reboot`.

Have you called `dracut -f` after TPM ownership changes? This could make a difference, because the actual `/var/lib/tpm/system.data` is being installed (it reflects TPM configuration). Otherwise please attach output of `sudo journalctl -b`.

2024-11-14 21:04 UTC, oldium commented
And I see that I need to add socat as a dependency to `clevis-systemd` RPM package, so this will be part of next build. I will create it when we find-out, what is wrong.

2024-11-14 21:46 UTC, akostadinov commented
I removed plymouth package and installed socat. Then ran unbind/bind, unlock works, then `dracut -fv`. To no avail unfortunately.
[dracut-output.txt.gz](https://github.com/user-attachments/files/17758202/dracut-output.txt.gz)
[journalctl-output.txt.gz](https://github.com/user-attachments/files/17758204/journalctl-output.txt.gz)

2024-11-15 00:27 UTC, oldium commented
Looks like a SystemD startup dependency issue, I will need to experiment with this. Do you have any custom modifications to SystemD units? And how does your /etc/crypttab looks like (if you have passwords here, replace them with *)?

2024-11-15 00:36 UTC, oldium commented
More precisely, it seems like if local-fs.target inside initrd environment depends on unlocked disk, so that tcsd is not started and disk not unlocked. I need to know how to reproduce this.

2024-11-15 08:09 UTC, akostadinov commented
I just installed Fedora server 41 from USB. I did almost no modifications. Installed tuned and removed zram-generator-defaults because using real swap. SSH setup... 

Maybe the only difference would be adding container tools at installation time. Also did custom partitioning. But not something non-standard. Basically one efi, one boot partition, and a LVM vg on a single pv which lives on top of the LUKS encrypted partition. And inside the vg I have one root and one swap logical volumes.

```
$ sudo cat /etc/crypttab 
luks-0a195438-f8da-412d-844c-fc98f40d31d2 UUID=0a195438-f8da-412d-844c-fc98f40d31d2 none discard

$ cat /etc/fstab
# ...
UUID=4900b22b-166c-48f8-8077-375e197894bc /                       xfs     defaults,x-systemd.device-timeout=0 0 0
UUID=9efecd9e-8fb1-4ea1-bdd5-54b7589856ad /boot                   xfs     defaults        0 0
UUID=FBEB-CFB2          /boot/efi               vfat    umask=0077,shortname=winnt 0 2
UUID=1bdecdba-e511-4d95-a48d-4b8488af9b7e none                    swap    defaults,x-systemd.device-timeout=0 0 0
```

2024-11-15 12:34 UTC, oldium commented
Thanks, I will try to reproduce this. Maybe this is about command-line arguments, maybe /etc/crypttab+fstab, who knows. I will try to get as close to your setup as possible (maybe faster would be to do another installation with custom partitioning - this could make the difference).

2024-11-15 14:31 UTC, akostadinov commented
From default kernel command line I have just removed `quiet` and `rhgb` options which should disable plymouth IIRC. But now I have plymouth removed anyway. I don't think they affect anything here.

Anyway, if you need further information, let me know. Or if you have some test builds to get the output of, that's also fine. I just installed this thing and nothing running on it to be bothered by rebooting.

2024-11-15 22:17 UTC, oldium commented
@akostadinov Definitely it is the swap device making the difference. I need to test the dependencies more thoroughly, especially differences during initrd and normal boot.

Anyway, the workaround should be to comment-out `After` and `Before` lines in `/usr/lib/systemd/system/tcsd.service.d/clevis-tcsd.conf`:

```
#After=local-fs.target
#Requires=local-fs.target
```

then run `dracut -f` and reboot should unlock the drives automatically.

I will come up with a solution after more playing with this. I need to ensure that `local-fs.target` dependency is not present in initrd environment, because the initrd filesystem is already ready (so no need to depend on local filesystem mount). Then I need to think about if using `local-fs.target` is the correct thing for the system boot environment. The `local-fs.target` is independent on `cryptsetup.target`, so usually it does not block starting the `tcsd`, but `swap` is part of `local-fs.target` (it is in /etc/fstab), so depending on `local-fs.target` delays start of `tcsd` after mounting `swap`, which is completely reversed (`swap` is encrypted).

2024-11-16 21:14 UTC, akostadinov commented
@oldium , that workaround helped! Thanks a lot! 

My setup is a little bit non-standard with swap because fedora by default ships with zram swap. But I'm somehow not convinced this is the best option.

Here's the log from a good startup:
[journalctl-output-good.txt.gz](https://github.com/user-attachments/files/17787309/journalctl-output-good.txt.gz)

I have run some tests like removing tpm2 pin and tpm2-tss modules from dracut, as well binding to unstable PCRs to make sure they matter. All seems to be working fine now.

Looking forward to test an updated version and hopefully see this feature merged soon!

2024-11-16 22:33 UTC, oldium commented
> @oldium , that workaround helped! Thanks a lot!

Good 👍

> My setup is a little bit non-standard with swap because fedora by default ships with zram swap. But I'm somehow not convinced this is the best option.
> 
> Here's the log from a good startup: [journalctl-output-good.txt.gz](https://github.com/user-attachments/files/17787309/journalctl-output-good.txt.gz)

Yep, it shows what I thought.

> I have run some tests like removing tpm2 pin and tpm2-tss modules from dracut, as well binding to unstable PCRs to make sure they matter. All seems to be working fine now.

The tpm2 functionality should have no influence since you are using tpm1. It is completely independent.

> Looking forward to test an updated version and hopefully see this feature merged soon!
> 
> P.S. wrt depending on local-fs, shouldn't it be the other way around? local filesystem to depend or at least be after tcsd? I think that whenever these services are run, the initrd fs should already be mounted. I can't imagine it otherwise 🤔

It depends. In initrd phase you have everything in-place, but during system boot phase you could have `/var` mounted from a separate partition, in which case `tcsd` has to wait for the mount (and ordering `After=local-fs.target` is clearly too late).

I have found that there is `WantsMountFor=` option, so I will test startup with this option.

There are several situations. The non-encrypted (or already unlocked) `/var` could be mounted before `tcsd` starts, but for the separately-encrypted `/var` case it would have to be unlocked and mounted from `initrd` already (option `x-initrd.mount` in `/etc/fstab`). I will need to play with this, I am curious how this is handled by SystemD 😁.

2024-11-17 10:25 UTC, akostadinov commented
I still don't understand. AFAIK first thing done by kernel is loading initrd at which point the whole stuff in it should be available, no? How comes var will already be mounted before initrd is available, be it encrypted or not?

Sounds to me like an exotic use case if that is the case. My opinion is that a full disk encryption is the most common use case. But it is reasonable to have some additional configuration like systemd unit parts in case of more exotic setups.

Alternative might be for tcsd not to be started by systemd dependencies directly but be part the clevis pin tpm1 code calling it in case it is not already running. Separation of concerns will not be great in this case but just brainstorming what could be done. I'm sure you have a better idea about how things work.

2024-11-17 13:27 UTC, oldium commented
> I still don't understand. AFAIK first thing done by kernel is loading initrd at which point the whole stuff in it should be available, no? How comes var will already be mounted before initrd is available, be it encrypted or not?

I am talking about initrd boot and system manager boot phases (see [man bootup](https://www.freedesktop.org/software/systemd/man/latest/bootup.html)). The initrd filesystem is specifically created during image creation and contains only things added by Dracut and Clevis, so there is a minimal version of `/var` suitable to run `tcsd` during initrd boot phase. The system's `/var` is not touched unless you _explicitly_ tell Dracut to unlock it (`x-initrd.attach` or undocumented `force` option in `/etc/crypttab`) and mount it (option `x-initrd.mount` in `/etc/fstab`). At the end of initrd boot phase all services are stopped and the sysroot `/sysroot` is switched to `/` and system manager boot phase starts by running all services from scratch. Here you can have the `/var` unlocked and mounted already (see the flags), or it needs to be done by SystemD. And this is where SystemD unit dependendencies start kicking in.

Anyway, it looks like that `WantsMountFor=` works just fine. There are still some rough edges inside Dracut itself to make it unlock the `/var` partition automatically in initrd phase, but that is definitely not about Clevis functionality any more.

> Alternative might be for tcsd not to be started by systemd dependencies directly but be part the clevis pin tpm1 code calling it in case it is not already running. Separation of concerns will not be great in this case but just brainstorming what could be done. I'm sure you have a better idea about how things work.

I do not want to solve SystemD service startup race by introducing another instance of `tcsd`. This is what `pkcs11` unlocking code does with `pcscd` service and I fear it. Because the Clevis ask-password service might be started at any time during boot as soon as SystemD decides to unlock the partition (because the ask-password service is started _after_ the password prompt is created), so it might collide with real `tcsd` service startup (or `pcscd` startup in `pkcs11` case). You do not have _any_ control over it. SystemD is here to control service startup, so I think the best is to let it do it.

2024-11-17 15:25 UTC, oldium commented
Note: Newer Dracut (v103+) is required for having a _separately-locked_ `/var`, because of [automatic unlocking](https://github.com/dracut-ng/dracut-ng/commit/2339acfaeee60d6bb26a1103db2e53bc8f9cb2d1) in v102 and [/etc/crypttab](https://github.com/dracut-ng/dracut-ng/commit/61ab3386e83a9bd219dcaa05c6499fec56d092b8) in v103 fixes. Config `/etc/fstab` needs to contain `x-initrd.mount` on the `/var` line. Also `hostonly=yes` together with `hostonly_cmdline=yes` in the Dracut config is necessary, plus having a cleaned-up `/etc/default/grub` kernel command line (no preconfigured `rd.lvm.*`, `rd.luks.*` arguments), otherwise it will not unlock automatically and mount... But those are Dracut-specific config issues, not Clevis-specific issues.

I tested both LVM-on-LUKS and LUKS-on-LVM scenarios for separately encrypted `/var`, I still need to test `/var` running on the same encrypted volume as root filesystem, but I expect this will work just fine with `x-initrd.mount` in `/etc/fstab`.

2024-11-17 16:44 UTC, akostadinov commented
Do I understand correctly that:
* if a filesystem has `x-initrd.mount` mount option, then it will be mounted during initrd phase
* that will happen as part of the `local-fs.target`
* if tcsd is started with the initrd minimal /var and real var is mounted on top of it, that will result in something very bad, that's why we want to start it after this possible early /var mount.
* WantsMountFor - undocumented option to try all mounts that will affect the /var mount so that they are performed before tcsd started (not sure how does this work when the encrypted /var needs the tcsd)

But then in case /var is encrypted (which would be the usual case probably), then the /var tcsd used will be mounted over anyway, after that var is unlocked, so perhaps it is not that bad. Or is it?

Please feel free to ignore my ramble. I assume you know better what you're doing.

2024-11-17 22:19 UTC, oldium commented
> Do I understand correctly that:
> 
> * if a filesystem has `x-initrd.mount` mount option, then it will be mounted during initrd phase

Correct. It will be mounted to `/sysroot/<mount>`, because `/sysroot` will eventually became the new root.

> * that will happen as part of the `local-fs.target`

This actually happens in initrd environment by `initrd-parse-etc.service` before reaching the `initrd-fs.target` inside the initrd phase. Just keep in mind that initrd and system manager bootup phases have similar targets (`local-fs.target` is also part of initrd phase) but are executed on different filesystems. Initrd's `local-fs.target` is about `/etc/fstab` present in the initramfs image, not about the system's one.

> * if tcsd is started with the initrd minimal /var and real var is mounted on top of it, that will result in something very bad, that's why we want to start it after this possible early /var mount.

As mentioned above, `/var` is mounted under `/sysroot`, which becomes new root `/` as the last step of initrd phase. There will be no conflict.

> * WantsMountFor - undocumented option to try all mounts that will affect the /var mount so that they are performed before tcsd started (not sure how does this work when the encrypted /var needs the tcsd)

Documented in [systemd.unit](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#WantsMountsFor=). The SystemD generates (via `systemd-fstab-generator`) SystemD units for each line of `/etc/fstab` very early while configuring bootup for the phase (definitely in the system manager bootup phase, but most probably _also_ in initrd bootup phase, but of course with `/etc/hosts` read from the corresponding filesystem). So during the system manager bootup phase the `/var` mount point will appear as SystemD unit (based on system's `/etc/hosts` value), so services can depend on it. Moreover, the `WantsMountsFor=` statement is clever, it automatically adds `Requires=` and `After=` for _all_ mount units required to access the specified path, which is in `tcsd` case `/var/lib/tpm`.
 
> But then in case /var is encrypted (which would be the usual case probably), then the /var tcsd used will be mounted over anyway, after that var is unlocked, so perhaps it is not that bad. Or is it?

Not really, `/var` and `/sysroot/var` are two different things, so `tcsd` handles once `/var` from initrd phase and once `/var` from system manager phase (this was `/sysroot/var` in initrd phase). The initrd as a last step simply makes a `chroot`-equivalent operation to switch to `/sysroot` as a new root `/`.
> 
> Please feel free to ignore my ramble. I assume you know better what you're doing.

It might seem that I know what I am doing, but I am actually still doing lot of experiments 😅

2024-11-17 22:51 UTC, oldium commented
More it sounds like `Wants=local-fs.target` dependency should be dropped from Clevis extension of `tcsd` because `WantsMountsFor=/var/lib/tpm` is more on target and allows starting early 😉 I am playing with new release currently.

2024-11-18 08:35 UTC, oldium commented
This will take some time, I would like to add a documentation about separately encrypted `/var` volume, so I need to test this also in `initramfs-tools` case.

2024-12-04 05:46 UTC, mauro2306 commented
Hi there, i recently tested the update 5 on another Kubuntu installation of another TPM 1.2 laptop, and it went fine. So it doesn't seem there is any regression with update 5 concerning Kubuntu 24.10 at least.
I saw you placed me as reviewer, i want to help but i can't comment on your code changes unfortunately, i am not that skilled to judge that part. But i can at least make some tests on random distros with one of my old laptop. I think i also have an old Lenovo that have TPM 1.2 only as well. How does that sound ?

2024-12-04 10:47 UTC, oldium commented
Ah, as always, application versions strike back. The `/var` solution works fine with SystemD 256+, but Debian 12 has SystemD 252, so I need to revert to the old (non `/var`-friendly) solution for old systems.

2024-12-05 22:30 UTC, oldium commented
Updated CentOS to stream10 version, EPEL10 is available (not yet officially announced it seems). EPEL10 does not contain [tpm-tools][1] (yet, hopefully).

[1]: https://pagure.io/epel/issue/311

2024-12-09 13:31 UTC, oldium commented
I did some final clean-up (reworked used-pins patch to allow running `clevis luks list -d <device> -p`) and tested it on usual VMs. I also did some more detailed separate-/var testing on Debian Trixie (initramfs-tools) and Fedora Rawhide (dracut) with LUKS on LVM and LVM on LUKS.

TBD: The last step, which is a result of my detailed testing, is to write a documentation on configuring separate-/var with Clevis. I will release update-6 afterwards.

Funny note - I have found that some tests fail to check the expected value - fixed here https://github.com/latchset/clevis/pull/462/commits/69638bd751643fb083d53e5a8ae0169c28c82baa

2024-12-11 01:18 UTC, oldium commented
I have released the [update 6](https://github.com/oldium/clevis/releases/tag/v21_tpm1u6). Enjoy 😁

New and Noteworthy:

* Fixed early startup to allow unlocking also swap devices.
* Allows unlocking with separate /var volume, see man clevis-encrypt-tpm1.
* Fixed running under Debian Trixie.
* Fedora-based distributions RPM has been synced with latest Rawhide RPM, so there are new packages `clevis-pin-tpm1` and `clevis-pin-pkcs11`. *Check installation instructions.*
* The RPM now contains a unique Vendor name (oldium), so the sticky-vendor flag can be used to prevent unwanted Clevis updates.

2024-12-11 01:29 UTC, oldium commented
The failed test usually takes few seconds, so the timeout might be caused by some other CI pipeline running on the same host...

2024-12-11 02:12 UTC, RadxaYuntian commented
> The failed test usually takes few seconds, so the timeout might be caused by some other CI pipeline running on the same host...

You can trigger a CI rerun in Checks tab of this PR.

2024-12-11 09:48 UTC, oldium commented
> > The failed test usually takes few seconds, so the timeout might be caused by some other CI pipeline running on the same host...
> 
> You can trigger a CI rerun in Checks tab of this PR.

There is no such option visible for me.

2024-12-11 09:52 UTC, sergio-correia commented
> > > The failed test usually takes few seconds, so the timeout might be caused by some other CI pipeline running on the same host...
> > 
> > 
> > You can trigger a CI rerun in Checks tab of this PR.
> 
> There is no such option visible for me.

I triggered a re-run of the failed test.

2025-01-01 00:00 UTC, oldium commented
Just a small change for the case if `initramfs-tools` will ever gets fixed with `UMASK=0077` - use `umask` command output instead of `UMASK` variable.

2025-01-27 09:56 UTC, oldium commented
Rebased and added TPM1 dependencies for CentOS Stream 10 (EPEL10 now contains tpm-tools).

Again, swtpm tests failed for TPM2, there must be some race condition (possibly unix socket forwarding with `socat`?), I need to play with it. All current build targets use `tpm2-tools` >= 3.2, so it should be possible to use unix sockets directly within `TPM2TOOLS_TCTI` env var without `socat` workaround.

2025-01-29 10:18 UTC, oldium commented
I have released the [update 7](https://github.com/oldium/clevis/releases/tag/v21_tpm1u7). Enjoy 😁

New and Noteworthy:

* Added CentOS Stream 10 package.
* Latest clevis updates.

2025-02-12 23:16 UTC, oldium commented
Rebased on latest master

2025-03-17 23:56 UTC, akostadinov approved these changes
I just performed a clean install on Fedora. Works like a charm. Thanks a lot!

Can any member of the repo review and get this merged? It's very useful to get skylake class machines running as they make quiet good servers.

2025-04-10 09:34 UTC, sarroutbi commented on src/initramfs-tools/scripts/local-top/clevis.in
> +        local pins=$(clevis_luks_read_used_pins "$CRYPTTAB_SOURCE")
I guess return code from `clevis_luks_read_used_pins` should be checked here and return 1 in case of error

2025-04-10 09:35 UTC, sarroutbi commented on src/luks/dracut/clevis/clevis-password-unlocker.in
> +        pins=$(clevis_luks_read_used_pins "$CRYPTTAB_SOURCE")
I guess return code from `clevis_luks_read_used_pins` should be checked here and return 1 in case of error

2025-04-10 09:37 UTC, sarroutbi commented on src/luks/clevis-luks-list
> +    echo "  -p      Print only a sorted space-separated list of bound pins" >&2
Should not this be rewritten to something like:
`Print only a sorted space-separated list of used pins bound to the specified device`

2025-04-10 09:39 UTC, sarroutbi requested changes
Thanks for the PR. Could you please review provided comments?

2025-04-10 10:37 UTC, sarroutbi commented
I have downloaded the code in this branch and tried to test it on a VM with TPM1 chip. I followed next steps:

1. Install dependencies:
```bash
sudo dnf install -y meson gcc clang cmake jose libjose-devel cryptsetup-devel socat trousers tpm-tools tpm2-tools luksmeta libluksmeta-devel
```
2. Installed clevis:
```bash
mkdir build; pushd build; meson setup --prefix=/usr --wipe ..; meson compile -v; sudo meson install; popd
```
3. Enabled tcsd daemon:
```bash
sudo systemctl enable --now tcsd.service
```
4. I checked status of tpm:
```bash
tpm_selftest 
  TPM Test Results: 53687574 646f776e 20303030 30303030 320a
```
5. TPM encryption/decryption is failing with next errors:
```bash
echo hi | clevis encrypt tpm1 '{}' 
Tspi_Context_LoadKeyByUUID failed: 0x00002020 - layer=tcs, code=0020 (32), Key not found in persistent storage
Unable to seal jwk
```
@oldium : Can you please provide some feedback about the process or commands to execute to verify what can be go wrong in my scenario? I am using Fedora 41

2025-04-10 10:44 UTC, akostadinov commented
@sarroutbi , did you start `tcsd.service` (not only enable it)? Did you run your commands as root?

2025-04-10 12:25 UTC, oldium commented
@sarroutbi Do you own the TPM? For fresh installations you need to call `tpm_takeownership --srk-well-known` and for existing ones `tpm_changeownerauth --srk --set-well-known` (as [documented](https://github.com/oldium/clevis/tree/feature/tpm1?tab=readme-ov-file#tpm1-pin-limitations)). You can check if TPM works correctly by issuing the same commands as TPM1 PIN:

```console
$ echo test | tpm_sealdata -z
-----BEGIN TSS-----
-----TSS KEY-----
AQEAAAARAAAABAEAAAABAAMAAQAAAAwAAAgAAAAAAgAAAAAAAAAAAAABALqHTk5k
/c9idJgjUD676OErez4BG2ZXX+kcMJYyD5l3sUuO+FbARcwHWDil5kOf1VwKEoBR
XLu1u6Cpo/+Ha8nDdmKEoSAmCL7cqF125jLeZPBqYlOm4R03FFp5ShUdp1UOLN0y
J+fQaE2C11R0JPrLqzao+6AMqkY3DVlY2EYnnUH4cJlSIvcxK3WDsXcNAI9Hr02a
Ku2hHXrXTrQlVKe+LEfyOQfqFij1ix+ApJ2nMh5lTwXgE4RZhCFRQdI5gjTTirAf
QBTQJnAgPYVbgxUOgjEN8She4y4Qks1cGjjrvGCYGuwvbbuZkU/3IJPXi05ZThQB
2/9fg4b65wh9YyEAAAEAcMH4BeLZyaYHwacvNYcZO3iE7q8ImjwvwuAbaF8b+1Ja
AFuNayK1fdwluCl0g0tvKz4WEdkDeYxA6Q4hhgL8yWquwnqGYG8vY7oAJIB8ONMj
FV3VVuVIVW2rUd2D4Kpgn0ErM79QJ8ULtSwVM03VPOsdCYce0coktQDiAvDyNkQk
ae046UrPYlznI37SQ/D+FCAW4kL/D6bc6QMPH2kgcBTdRYhLhBQ4uWkpf6+DfFi2
D7ZXVTQp7+adObiYDc0Gd9YRV2JLW3e017Yls7ky8Ks8AHDyF4QuHvta5gRrrAO6
LMB9sZTVtZZEsUf7psUH2Aa3B4j8pm/FrEiF6s0zvQ==
-----ENC KEY-----
Symmetric Key: AES-256-CBC
AQEAAAAAAAAAAAEAJyeDJqzvS0avmsYyEMfVN8PhPhS5TWr5nmwu8RWg9Yd9Jzov
buMg9tfOK7EGiMo+tnspYlKzszuFY922VN3NAT6do5prqao7+/jp3legzczXCj9V
MZdels6WeoobRyXHrFXHkAuCmXuVF9xw/LTsEuTuLkLCgqUXZY2C/93VSZNPFrQs
4Rr763HIKPgnLSS6SRVPqGN0BAihVBbUQ9FGAtOZfwbNaX3QMYtxRGs+r/ylDN0w
MznfDPhUnvxuUFToqQK8kZRbXB4x8TnlfgB7RJ3m6CX58RAefLJaPG+oU5YG84bX
rvPDf2QMrek4xyhe8RGiFfKeLDtI+RgrZEOs1Q==
-----ENC DAT-----
LZq+S5A2z6ybFhGU2KK3kA==
-----END TSS-----
```

If you still see error even after taking ownership, there might be problem with your `/var/lib/tpm/system.data`.

2025-04-10 12:31 UTC, oldium commented
> Thanks for the PR. Could you please review provided comments?

Yes, thanks for review, I will update the commits.

2025-04-10 13:25 UTC, oldium commented on src/luks/dracut/clevis/clevis-password-unlocker.in
> +        pins=$(clevis_luks_read_used_pins "$CRYPTTAB_SOURCE")
Yes, most probably. I will also check [this code](https://github.com/latchset/clevis/pull/462/commits/ac6a8f5cf4b0f7bfcd1ea24e243456f2cd747783#diff-5f997d83fbf5fafdd8047dbd41cdb8e4bf41d4cc68abc59074bc47a1cddcde66R55), which after all that time looks suspicious to me too.

2025-04-10 13:35 UTC, sarroutbi commented
After fixing TPM ownership I was able to boot with TPM1 simulated chip in VM so changes LGTM.

After including suggested changes, please, let's wait for @sergio-correia review in order to double check this.

Thanks again @oldium for this great contribution

2025-04-15 09:28 UTC, sergio-correia requested changes
Thanks, very impressive work -- it looks very good overall. I added a couple of nit comments to improve consistency.

2025-04-15 09:28 UTC, sergio-correia commented on src/pins/tpm1/clevis-tpm1-tcsd-preload.c
> +{
Nit: you should follow the style of the other functions in this file, for consistency.

2025-04-15 09:28 UTC, sergio-correia commented on src/luks/clevis-luks-common-functions.in
> +function clevis_kill_pid() {
Nit: there is no need for the `function` keyword. We probably still have a couple functions with it in this file, but let's not add more and instead remove the other ones later :)

2025-04-16 22:47 UTC, oldium commented
Thanks for reviews, I will incorporate all review comments, I just need to find some time for that 😊

2025-05-03 10:24 UTC, oldium commented
Just a small update - my other pet project (deb/rpm repo builder for home usage using reprepro/createrepo_c tools) is almost finished, so I will get to this shortly.

2025-05-03 10:30 UTC, sarroutbi commented
> Just a small update - my other pet project (deb/rpm repo builder for home usage using reprepro/createrepo_c tools) is almost finished, so I will get to this shortly.

Sure. Take your time, as we did for reviewing the PR :smile:

2025-09-14 08:19 UTC, aadnehovda commented
Would this play nicely together with #467? Anything missing? Great for proxmox ZFS root on older TPM 1.2 only hardware.

2025-09-14 08:39 UTC, oldium commented
> Would this play nicely together with #467? Anything missing? Great for proxmox ZFS root on older TPM 1.2 only hardware.

Hard to say without looking more into the ZFS support. I see some code duplication in the ZFS initramfs hook, it installs basically the same binaries as the regular clevis hook. It misses TPM1.2 completely (for obvious reasons).

From the brief look I was not able to tell how exactly the ZFS unlocking works, but if it uses the same clevis functionality to decrypt the password, it should (in theory) work.

Side note: I have rebased my patches and changed them according to code-review input plus few fixes more (also for easier packaging of the new `file` pin in Debian). I will send an update within a week or two after testing it.

2025-09-14 08:52 UTC, oldium commented
Possibly there will be some startup changes necessary to line-up with the ZFS support, because the clevis initramfs `local-top` script just starts the `tcsd` (TPM1.2 daemon) only in case the `tpm1` pin is detected by `get_pid_device_pins` function (again, I do not know how the ZFS integration works). For `dracut` startup I can imagine missing optional startup dependency on `tcsd`.

Anyway, nothing impossible to do.

2025-11-16 21:11 UTC, oldium commented
Added several `fixup!` commits ready to be rebased after code review. It is ready to go one-by-one, the commits are small and self-explanatory.

On top of the code-review fixes, I added the following:

* Few additional safety checks and local variable declarations.
* Fixed usage of uninitialized variable in tpm2/tpm1 test code (the test did not test what it should test for a looooooong time...).
* Fixed new `template` and `file` pins to allow installation under Debian. Debian installs all Dracut scripts and uses `check()` function to determine if the pin is actually installed on the system.

On top of that, I created a [new `tpm1u8` version](https://github.com/oldium/clevis/releases/tag/v21_tpm1u8) and published GPG signed packages in the public repository – see the Release Notes.

2025-12-12 10:32 UTC, sarroutbi approved these changes
LGTM. Thanks for your PR. @sergio-correia : A double opinion is welcome here

2025-12-12 13:27 UTC, oldium commented
Just a kind reminder: Please do not merge without auto-squashing first (`git rebase --autosquash`), I would be sad to have the commit history in this state 😁. I would like to do it when the reviews are finished.

2026-02-11 17:30 UTC, oldium commented on src/initramfs-tools/hooks/clevis.in
> +    for rule in 60-tpm-udev.rules; do
That is a common pattern in other files, multiple rules mean multiple files.

2026-02-11 17:34 UTC, oldium commented on src/luks/dracut/clevis-pin-tpm1/module-setup.sh.in
> +        if [ ! -f "$initdir/etc/hosts" ]; then
setting `initdir` is a responsibility of Dracut

2026-02-11 17:35 UTC, oldium commented on src/luks/dracut/clevis/clevis-password-unlocker-prepare.in
> +for askpass in "$hookdir"/initqueue/settled/cryptroot-ask-*.sh; do
setting `hookdir` is responsibility of Dracut

2026-02-11 17:36 UTC, oldium commented on src/luks/dracut/clevis/clevis-password-unlocker-prepare.in
> +        detectedfile="/tmp/clevis-device-detected-${device//\//_}"
this is run under Bash, so is fine

2026-02-11 17:36 UTC, oldium commented on src/luks/dracut/clevis/clevis-password-unlocker-prepare.in
> +        if [[ " $pins " == *" tang "* ]] && getargbool 0 rd.neednet && [ ! -f /run/clevis-online ]; then
this is run under Bash, so is fine

2026-02-11 17:36 UTC, oldium commented on src/luks/dracut/clevis/clevis-password-unlocker-prepare.in
> +            mv -f "${askpass}" "${askpass/settled/online}"
this is run under Bash, so is fine

2026-02-11 17:37 UTC, oldium commented on src/luks/dracut/clevis/clevis-password-unlocker-prepare.in
> +        pipepath="${pipeprefix}/pipe-${device//\//_}"
this is run under Bash, so is fine

2026-02-11 18:19 UTC, akostadinov commented
Who needs to approve this PR for merge?

2026-02-18 12:05 UTC, sarroutbi commented
> Who needs to approve this PR for merge?

Changes LGTM. Waiting for @sergio-correia to check if anything else is required (it seems all suggested nits were resolved)

2026-04-14 11:10 UTC, oldium commented
[Updated]

@sarroutbi I am testing the rebase and almost everything works. Unfortunately, the newest Ubuntu 26.04 is using Dracut 110, which renumbered the [systemd-cryptsetup](https://github.com/dracut-ng/dracut-ng/commit/d7bdbbb702abcd9c141decd0160284ad22a8b253) module from 11 to 71, so we cannot add “needs” for `cryptsetup.target`, which is installed _after_ clevis (we were 60, currently 50). The Dracut change breaks actually all versions of `clevis-dracut` - I am talking about this [line](https://github.com/latchset/clevis/blob/master/src/luks/dracut/clevis/module-setup.sh.in#L44), we do not depend on `systemd-cryptsetup` intentionally to allow installation without systemd. So either we switch some code to 90-99 range (not recommended for general use, but for adding one “needs” it would suffice), or create a bug report in Dracut repo, or think about a different solution...

Hm, or maybe I am wrong. Dracut has 00systemd, which installs cryptsetup.target. Let me check more...

[Edit]
00systemd is not installed - it is in old dracut repo, not dracut-ng...

2026-04-14 14:21 UTC, sergio-correia requested changes
@oldium: Thanks, I finally had a chance to review this again. Looks very nice, but I pointed a few small issues to fix. Please, also rebase on top of the current master. Also, are you going to autosquash those fixup commits?

2026-04-14 14:21 UTC, sergio-correia commented on src/initramfs-tools/hooks/clevis.in
> +    copy_file config /etc/tcsd.conf || dia 2 "Unable to copy /etc/tcsd.conf"
Typo here: should be `die` instead of `dia`

2026-04-14 14:21 UTC, sergio-correia commented on src/initramfs-tools/hooks/clevis.in
> +    group_id=`id -G tss` || die 2 "Unable to get tss group ID"
Isn't this supposed to be `id -g` (lowercase), to return all groups instead of primary GID?

2026-04-14 14:21 UTC, sergio-correia commented on src/pins/tpm1/clevis-encrypt-tpm1
> +        local pcr_args="${pcr_ids:+-p}${pcr_ids//,/ -p}"
I believe we should use `$_pcrs` (which we define in this `validate_pcrs()` function) here; we are using the "outer" `$pcr_ids` instead, whihc seems to work by coincidence.

2026-04-14 14:21 UTC, sergio-correia commented on src/tests-common-functions
> +            error "Timeout (${max_timeout_in_s}s) waiting for ${name:process}"
`${name:process}` should be `${name:-process}` (missing the dash for the default value), in those two instances here.

2026-04-14 14:21 UTC, sergio-correia commented on src/pins/tpm1/clevis-tpm1-tcsd-preload.c
> +    static int (*real_setgid)(uid_t) = NULL;
`gid_t` instead of `uid_t` here.

2026-04-14 14:21 UTC, sergio-correia commented on src/pins/tpm1/clevis-tpm1-tcsd-preload.c
> +    return 0;
This `return` is unreachable, please just remove it.

2026-04-14 14:21 UTC, sergio-correia commented on src/pins/tpm1/tests/pin-tpm1-tests
> +        echo "${TEST}: encrypt failed for cfg: ${cfg}" >&1
This should probably be `>&2`

2026-04-14 14:30 UTC, oldium commented
Thanks @sergio-correia for the review, I now feel like a kid. I saw the code so many times and have not noticed that 😅. I will fix all your findings and auto-squash it.

2026-04-14 17:12 UTC, oldium commented
The issue with Dracut 110 is reported here https://github.com/latchset/clevis/issues/545

2026-04-15 14:44 UTC, guilherme-puida commented
I commented this in #545 as well, but clevis 20-1ubuntu2 was uploaded with a patch that fixes the ordering issue.

2026-04-16 22:18 UTC, oldium commented
I will rebase onto #549 to create a non-conflicting branch.

2026-04-17 09:21 UTC, oldium commented on src/initramfs-tools/hooks/clevis.in
> +    group_id=`id -G tss` || die 2 "Unable to get tss group ID"
The `id -G` is actually returning all groups, so this might form an invalid entry (not usually the case, `tss` is a system user created during package installation with single group `tss`). This usage is specifically about the group ID of the `tss` group, so getting it through the primary group of `tss` user is the way to go - `id -g tss` should be used.

2026-04-17 09:40 UTC, oldium commented on src/pins/tpm1/tests/pin-tpm1-tests
> +        echo "${TEST}: encrypt failed for cfg: ${cfg}" >&1
Actually, a copy-paste from tpm2 pin test 🙈 Fixing it there too.

2026-04-17 19:19 UTC, oldium commented
Updated, rebased, autosquashed. Ready to be merged 😊

2026-04-17 19:27 UTC, oldium commented
Latest release v22_tpm1 is here https://github.com/oldium/clevis/releases/tag/v22_tpm1 as usual.

Built images:

* Debian: 14 (Forky), 13 (Trixie), 12 (Bookworm), 11 (Bullseye)
* Ubuntu: 26.04 (Resolute Raccoon), 25.10 (Questing Quokka), 24.04 (Noble Numbat)
* CentOS: Stream 10, Stream 9
* Fedora: 45, 44, 43, 42, 41, 40, 39

2026-04-18 17:39 UTC, sergio-correia commented on src/pins/tpm1/clevis-encrypt-tpm1
> +        local pcr_args="${_pcrs:+-p}${_pcrs//,/ -p}"
Just to double check: is this `pcr_args` supposed to be used? I noticed that further down you use `_pcrs` directly with `tpm_sealdata`.

2026-04-18 18:24 UTC, oldium commented on src/pins/tpm1/clevis-encrypt-tpm1
> +        local pcr_args="${_pcrs:+-p}${_pcrs//,/ -p}"
Aargh, you are completely right. This has to be translated to `-p`, so `pcr_args` should be used...

2026-04-18 18:25 UTC, oldium commented on src/pins/tpm1/clevis-encrypt-tpm1
> +        local pcr_args="${_pcrs:+-p}${_pcrs//,/ -p}"
Thanks for the review, really appreciated! Will fix asap.

2026-04-18 18:33 UTC, oldium commented on src/pins/tpm1/clevis-encrypt-tpm1
> +        local pcr_args="${_pcrs:+-p}${_pcrs//,/ -p}"
Fixed

2026-04-18 18:38 UTC, oldium commented
New packages with fixed PCR validation will arrive soon.

2026-04-18 22:19 UTC, sergio-correia approved these changes
Very nice job, thank you! I will merge this.

2026-04-18 22:19 UTC, merged

2026-04-18 22:46 UTC, oldium commented
One small step for a man, one giant leap for mankind 😁

Thank you very much!

2026-04-20 17:53 UTC, akostadinov commented
Thank you @oldium , now we can run our old gear for another 15 years!

2026-04-20 20:54 UTC, oldium commented
That was the goal! 😂

2026-04-21 21:05 UTC, oldium commented
Latest release v22_tpm1u1 is here https://github.com/oldium/clevis/releases/tag/v22_tpm1u1 as usual.

Built images:

* Debian: 14 (Forky), 13 (Trixie), 12 (Bookworm), 11 (Bullseye)
* Ubuntu: 26.04 (Resolute Raccoon), 25.10 (Questing Quokka), 24.04 (Noble Numbat)
* CentOS: Stream 10, Stream 9
* Fedora: 45, 44, 43, 42, 41, 40, 39

2026-10-01 14:18 UTC, akostadinov commented
Which official release did this end up into? To check if my distro picked that up.

Thank you again @oldium for implementing this and following through the whole process!

Update: I found the commits in v23